baseURL = "https://nialljmiller.github.io/custom-colors_mesa-school-labs/"
languageCode = 'en-us'
title = 'MESA Custom Colors Lab'
theme = 'Hextra'

[params.search]
enable = false

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['$', '$']]